// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydsjwkqeyfmsmbcybycg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlkc2p3a3FleWZtc21iY3lieWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjcxMzMsImV4cCI6MjA2OTQwMzEzM30.0m_QumMRM321RhkiklQECn-BtakUXEwMMsg1ke50GrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});